CLI_NAME = "omnicontext"
PACKAGE_NAME = "omnicontext"
ENV_BRANCH = "OMNICONTEXT_BRANCH"

GIT_DIR = ".git"
HOOK_NAME = "post-checkout"
HOOK_MARKER = "# omnicontext-managed"
DEFAULT_SOUND_FILE = "notification.oga"
DEFAULT_SYNC_PROVIDER = "local"

CONFIG_DIR = ".omnicontext"
CONFIG_FILE = "config.json"
TEMPLATE_DIR = "template"
BRANCHES_DIR = "branches"
DEFAULT_SYMLINK = ".branch-context"
